### ISSUE TITLE
Cannot read property 'theme' of undefined

### ISSUE THREAD

**Issue by nandoflorestan** [axe-me/vite-plugin-tailwind#2]
I am getting the following error:

```
[vite] Internal server error: Cannot read property 'theme' of undefined
  Plugin: vite:css
  File: /home/nando/py/jobs/fairsplit/fair/fair/ui/src/App.module.css
      at _default (/home/nando/py/jobs/fairsplit/fair/fair/ui/node_modules/tailwindcss/lib/lib/substituteScreenAtRules.js:16:5)
      at /home/nando/py/jobs/fairsplit/fair/fair/ui/node_modules/@tailwindcss/jit/src/index.js:50:11
      at LazyResult.runOnRoot (/home/nando/py/jobs/fairsplit/fair/fair/ui/node_modules/postcss/lib/lazy-result.js:339:16)
      at LazyResult.runAsync (/home/nando/py/jobs/fairsplit/fair/fair/ui/node_modules/postcss/lib/lazy-result.js:391:26)
      at LazyResult.async (/home/nando/py/jobs/fairsplit/fair/fair/ui/node_modules/postcss/lib/lazy-result.js:221:30)
      at LazyResult.then (/home/nando/py/jobs/fairsplit/fair/fair/ui/node_modules/postcss/lib/lazy-result.js:206:17)
```

I could be wrong, but I believe the problem is, vite-plugin-tailwind should not be using the dependency https://github.com/tailwindlabs/tailwindcss-jit anymore -- if you visit that, you'll see a prominent notice:

**As of Tailwind CSS v2.1 this project has been merged with the core Tailwind CSS repository and all future development will happen there.**

So I could be wrong, but I think this plugin is currently broken.

I do have a tailwind.config.ts file at the root of my project which contains:

```
export default {
	mode: 'jit',
	purge: [],
	darkMode: false, // or 'media' or 'class'
	theme: {
	  extend: {},
	},
	variants: {},
	plugins: [],
}
```

Any help appreciated.

**Comment by vaseala** [comment]
@nandoflorestan
https://github.com/sveltejs/svelte-loader/issues/188#issuecomment-868709873

**Comment by nandoflorestan** [comment]
Because I had no answer for 17 days I switched to WindiCSS.
